"🌶️ green donut":
  - "src/GreenDonut/**/*"
"🌶️ hot chocolate":
  - "src/HotChocolate/**/*"
"🌶️ marshmallow pie":
  - "src/MarshmallowPie/**/*"
"🌶️ strawberry shake":
  - "src/StrawberryShake/**/*"
"🧰 maintenance":
  - ".build/**/*"
  - ".github/**/*"
  - ".devops/**/*"
"📚 documentation":
  - "website/src/docs/**/*.md"
  - "website/src/docs/**/*.mdx"
