"🌶️ green donut":
  - "src/GreenDonut/**/*"
"🌶️ hot chocolate":
  - "src/HotChocolate/**/*"
"🌶️ marshmallow pie":
  - "src/MarshmallowPie/**/*"
"🌶️ strawberry shake":
  - "src/StrawberryShake/**/*"
"🌶️ website":
  - "website/**/*"
  - "!website/src/docs/**/*.md"
  - "!website/src/docs/**/*.mdx"
"📚 documentation":
  - "website/src/docs/**/*.md"
  - "website/src/docs/**/*.mdx"
"🧰 maintenance":
  - ".build/**/*"
  - ".github/**/*"
  - ".devops/**/*"
