"🌶️ green donut":
  - "src/GreenDonut/**/*"
"🌶️ hot chocolate":
  - "src/HotChocolate/**/*"
"🌶️ marshmallow pie":
  - "src/MarshmallowPie/**/*"
"🌶️ strawberry shake":
  - "src/StrawberryShake/**/*"
# "🌶️ website":
#   - any: ["website/**/*"]
#   - all: ["!website/src/docs/**/*.md", "!website/src/docs/**/*.mdx"]
"🧰 maintenance":
  - ".build/**/*"
  - ".github/**/*"
  - ".devops/**/*"
"📚 documentation":
  - any: ["website/src/docs/**/*.md", "website/src/docs/**/*.mdx"]
